[package]
name = "adder"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@elrond.com>"]
edition = "2018"
publish = false

[lib]
path = "src/adder.rs"

[features]
wasm-output-mode = ["elrond-wasm-node"]

[dependencies.elrond-wasm]
version = "0.19.1"
features = ["derive"]

[dependencies.elrond-wasm-node]
version = "0.19.1"
optional = true

[dev-dependencies.elrond-wasm-debug]
version = "0.19.1"
