[package]
name = "enonfungibletokens-meta"
version = "0.0.0"
authors = ["andrei-marinica <andrei.marinica@elrond.com>"]
edition = "2018"
publish = false

[dependencies.enonfungibletokens]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.30.0"
