[package]
name = "adder-abi"
version = "0.0.0"
authors = ["Andrei Marinica <andrei.marinica@elrond.com>"]
edition = "2018"
publish = false

[dependencies.adder]
path = ".."

[dependencies.elrond-wasm]
version = "0.20.1"


[dependencies.elrond-wasm-debug]
version = "0.20.1"

